# Site settings
title: Carlos Eriksson
email: carlos@carloseriksson.com
description: "Online journal of multilingual designer and frontend developer Carlos Eriksson. He sometimes makes websites, sometimes not."
baseurl: ""
url: "http://carloseriksson.com"
twitter_username: fiinixdesign
github_username:  fiinix

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
future: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      cta-copy: "Share your thoughts and comments"
      cta-label: "on Facebook"
      cta-label2: "on Twitter"
      cta-url: "https://www.facebook.com/fiinixdesign/"
      cta-url2: "https://twitter.com/fiinixdesign"

# Gems
gems:
  - jekyll-redirect-from

# Sass settings
sass:
    style:  compressed  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory
