# Site settings
title: Carlos Eriksson
email: carlos@carloseriksson.com
description: "Online journal of multilingual designer and frontend developer Carlos Eriksson. He sometimes makes websites, sometimes not."
baseurl: ""
url: "http://carloseriksson.com"
twitter_username: fiinixdesign
github_username:  fiinix

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
future: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      cta-default-start: 2019-09-01
      cta-default-end: 2019-09-30
      cta-default-copy: "Did you know?"
      cta-default-label: "My novella, Tales from the Gun is out now"
      cta-default-url: "http://carloseriksson.com/tales-from-the-gun"

# Gems
gems:
  - jekyll-redirect-from

# Sass settings
sass:
    style:  compressed  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory
